### ISSUE TITLE
laser 1.3 moves instantly no matter what thinking time is set

### ISSUE THREAD

**Issue by gpaunica** [jeffreyan11/uci-chess-engine#1]
Hello,
I have downloaded Laser 1.3 chess engine and it always moves instantly, no matter what tkinking time is set. And if I may ask you another thing: The EvalCache UCI option that is having the maximum value 1048576 what represents this number (Kb, Mb...)?
The GUI which I am using is Aquarium 2016.
My PC specs if it matters are:
CPU: INTEL I5 6600K
RAM: 8GB DDR4 @ 2400MHz
MB: MSI Z170A PC MATE
Please help me.
Thanks a lot.

**Comment by jeffreyan11** [comment]
Hi,
I have never tested with Aquarium but I will look into this over the next few days - thanks for letting me know. I probably won't make a separate bugfix release, however, so you may have to wait until the next release.

The EvalCache option is in MB.

**Comment by jeffreyan11** [comment]
Hi,
I have now released Laser 1.4 which hopefully fixes the bug. Let me know if you run into any other issues.

Jeffrey

**Comment by gpaunica** [comment]
Thanks a lot, it is working great now.
Again thanks.

2017-05-11 12:33 GMT+03:00 Jeffrey An <notifications@github.com>:
