### ISSUE TITLE
PVS() may return false MATE scores

### ISSUE THREAD

**Issue by AndyGrant** [jeffreyan11/uci-chess-engine#14]
It appears to me that it is possible, when no ttMove is present, for every move to be pruned without being searched in PVS(), thus resulting in movesSearched = 0, and then a mate score being returned.

I tested locally adding this condition to moveIsPrunabled : movesSearched > 0
889 - 883 - 1596  [0.501] 3368 @ 5s+.05s

Seems unintended.

**Comment by jeffreyan11** [comment]
This was covered by the bestScore > -INFTY condition, but I cleaned up some of the near-mate pruning logic with https://github.com/jeffreyan11/uci-chess-engine/commit/c97a2473771d481e20d2589004cd69960d4c8491.
