### ISSUE TITLE
Laser 1.6b for Linux on SDChess website from Russia

### ISSUE THREAD

**Issue by yellow-panther** [jeffreyan11/uci-chess-engine#16]
Hello,

is http://www.sdchess.ru/engines/laser_1_6b.zip an official release or not? What´s about 1.6 win64 bit engine?

**Comment by jeffreyan11** [comment]
No, this is not an official release. Official releases will be Windows 64-bit, and found at https://github.com/jeffreyan11/uci-chess-engine/releases.
