### ISSUE TITLE
Too many system calls

### ISSUE THREAD

**Issue by AndyGrant** [jeffreyan11/uci-chess-engine#27]
http://talkchess.com/forum3/viewtopic.php?f=7&t=65726

Long ago I fixed this locally by limiting the check rate for calling systemTime.

You've changed things, so I don't know where to look this time. 

@noobpwnftw gets less than 50% of expected NPS while running your engine in parallel. 

It is an issue with server-grade Intel CPUs, so we cannot reproduce on our thread rippers.

**Comment by jeffreyan11** [comment]
Pushed b5e4b2161c92958ff3a41d963c6a834479098d4b to fix the problem. Let me know if it didn't work.

**Comment by AndyGrant** [comment]
Appears to have worked. Last test I saw with Laser had proper NPS on noobpwn machines.
