### ISSUE TITLE
v1.5 Windows executables including source code

### ISSUE THREAD

**Issue by yellow-panther** [jeffreyan11/uci-chess-engine#4]
Hello Jeffrey and Michael,,

on the Russian **SDChess website** http://www.sdchess.ru/download_engines.htm v1.5 for Linux is mentioned, but not on **GitHub** https://github.com/jeffreyan11/uci-chess-engine/
- why? Are existing Windows binaries 32/64 bit (anywhere) of edition 1.5?

**Comment by jeffreyan11** [comment]
Hi,

There is no official release of version 1.5. We refer to any source code published here as 1.5 beta, so I believe the website is referring to their own compile of the most recent source code.
