### ISSUE TITLE
"PrintStatistics() & Searchmoves" problems

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jeffreyan11/uci-chess-engine#5]
Hi,
your program prints some statistics on "bestmove". Looking at the code its comes from this PrintStatistics() function.
Can this be removed? I also checked Laser11 (=same). Or at least have a flag for it in the makefile to disable/enable it (should be off by default).
It gives some problems to python-chess and from the uci api, it seems to not be allowed this way?!?

Next:
it seems to me that the engine doesnt support "searchmoves" as parameter of "go". Is that correct?
I need this to use "alternative move". Which doesnt work with your engine (SF f.e. is OK).
If its not inside, how are chances it will come (soon)?

Jürgen

**Comment by jeffreyan11** [comment]
Hi,

The UCI protocol says nothing about usage of standard error, which is what this output uses. However, I can turn this off by default if it gives some programs trouble.

You are correct that Laser does not have the full UCI spec, including features such as searchmoves, pondering, and search nodes. searchmoves should be easy to implement so this can be added soon (I will probably have it within a month or two).

**Comment by LocutusOfPenguin** [comment]
thanks.
perhaps this cerr isnt a problem , lets see. I also asked niklasf for a comment
https://github.com/niklasf/python-chess/issues/163

That "go ponder" is not implemented is right now a K.O. criteria for picochess. But i need to do some homework and check for the ponder flag, aehm. Anyway, i think, this is alot (alot) more important as searchmoves (i have overlooked this miss).

Last i would like to suggest (y can simply ignore it, if y dont agree).
If y do a "board", y get a compressed display of a board. I like the python-chess way more, with spaces between a-h and with "." instead of " " for an empty space. But its only a suggestion!

Jürgen

**Comment by LocutusOfPenguin** [comment]
ok, dont need to change this "cerr" and for the K.O. i updated my source code abit (but now rodent3 is a problem, ha).

**Comment by LocutusOfPenguin** [comment]
close this, for the rest i opened a new one. Thx!
