### ISSUE TITLE
Feature Request: support some missing uci parameters

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jeffreyan11/uci-chess-engine#6]
Hi,
i split this in two issues, and close the first #5.

Please consider to support "go searchmoves", and "ponder" flag & "ponderhit"
Some comments already done in this old issue.

Jürgen

**Comment by jeffreyan11** [comment]
Both go searchmoves and ponder have been implemented now. There may still be some bugs, especially in pondering, but feel free to try things out.
